[package]
name = "betterchars"
version = "0.1.0"
edition = "2021"

keywords = ["rust-patterns", "parsing", "no-std"]

description = "std::str::Chars, but improved"
readme = "README.md"

[dependencies]
