[package]
name = "betterchars"
version = "0.1.4"
edition = "2021"

keywords = ["rust-patterns", "parsing", "no-std"]
license = "MIT"

description = "std::str::Chars, but improved"
repository = "https://github.com/SamuelMcGowan/betterchars"
readme = "README.md"

[dependencies]
